### ISSUE TITLE
[Suggestion] Valves and switches

### ISSUE THREAD

**Issue by EzerArch** [mekanism-mod/Mekanism#3256]
Bringing a suggestion from an old, closed issue: #2375, for until now it's never got an issue of its own.

> Suggestion: wouldn't it be better if Mekanism had valves instead of levers cutting off pipes? http://en.wikipedia.org/wiki/Valve -- @EzerArch

And:

> By the way, I love the idea of valves. Definitely considering! -- @aidancbrady 

I propose implementing valves for pipes and, perhaps, switches for cables:

So, instead of using levers cutting off pipes, like this:

![2016-05-23_01 20 23](https://cloud.githubusercontent.com/assets/6743303/15460246/08c986ba-2085-11e6-89ae-078b4f888cb7.png)

It would be like this:

![2016-05-23_01 20 11](https://cloud.githubusercontent.com/assets/6743303/15460484/e06d1e68-2087-11e6-9919-292a1a359ca6.png)(made with microblocks and some image editing)

Features, specially for sake of simplicity:
- Fits in a 1-block length, and no much wider than a pipe/cable cross-section.
- Can't be placed in junctions or turns. Only in straight lines.
- Two states: on/open (green light) and off/closed (red light).
- Can be switched by hand (right-click). No need of levers (saves 1 block space).
- Can be controlled by redstone.

**Comment by EzerArch** [comment]
(not necessary to reply) @aidancbrady or any other dev, just a question out of curiosity:
>* _**Removing redstone sensitivity in transmitters**_, adding in some kind of "transmitter switch" to function as @EzerArch suggested -- https://github.com/aidancbrady/Mekanism/issues/3283#issuecomment-222329933

Do the current transmitter blocks (cables and pipes) perform some kind of redstone check every tic/loop? If they do, I suppose that this could be a source of lag, as I've read [here](https://github.com/micdoodle8/Galacticraft/issues/2129#issuecomment-195758913). So I guess that removing redstone sensitivity from transmitters and limiting it to a specific block would be an improvement performance-wise, wouldn't it?

**Comment by aidancbrady** [comment]
Luckily, no- redstone sensitivity is purely event-based. That's not to say removing sensitivity wouldn't make things more efficient- it certainly would.

**Comment by rdunham3** [comment]
Responding to this thread instead of creating a new one because it seems related.  I've had a few layouts where I wished for a way to set a preferred path for the fluid/gas being transported with an alternative path for overflow if the preferred path couldn't accept any more, but didn't want it enough to try to finagle a redstone switching method because those are usually so bulky.  I understand that items have the restrictive and diversion transporter pipes (although I've never wanted to do this with items, oddly, only fluids/gases) but as far as I am aware fluids and gases don't have an equivalent.
