### ISSUE TITLE
[Feature Request] Mek Pipes in One Block + New Pipe Type

### ISSUE THREAD

**Issue by Utildayael** [mekanism-mod/Mekanism#3754]
I'm not sure if this goes against your philosophy for what you want Mekanism to look like @aidancbrady  but I thought I would suggest it as it is, by far, the single coolest thing in EnderIO and I haven't seen a single other mod do this.

Pipes in one block!

If you've used EnderIO you already know exactly what I'm talking about. You can run say an item pipe, a fluid pipe, and a power pipe all in the same space and even connect all of them to a machine/inventory/etc. This is insanely handy for trying to make clean and compact builds or for complicated builds. [I use them for my PRC all the time for example tho that's a bit better now that you let us pick what sides do what but I digress...]

---

Additionally... a new pipe type that would be very useful would be a redstone pipe. Name says it all. Pipe that carries a redstone signal. Bonus points if it can do multiple channels like the EnderIO ones. Why make it? Many machines and processes in Mekanism can work off a redstone signal but you have to get that signal TO the machines/tanks/etc. Using redstone dust is pedestrian! 

---

I realize both of these are not "trivial" additions and would require retooling quite a few things but I wanted to submit them for your review for possible future implementation much like the MekaSuit. :)

Cheers!

**Comment by VT-14** [comment]
Why not just use Ender IO's conduits?  I realize there has been some incompatibilities based on RF api choice, but that will get straitened out once one api becomes the standard (like RF is supposed to be).

Your suggestion would require completely reworking all the cables/pipes in Mekanism to blatantly rip off another mod.  Multiple pipes in a single block is really cool, but it's also definitely Ender IO's thing.

Mekanism could get away with a similar function by providing limited multi-use pipes; like gas pipes that can also transfer power.  I would suggest keeping the limits to 2 uses (no power, fluid, gas, and item transferring pipes).

**Comment by Utildayael** [comment]
Why Mek? Because I don't want to use EnderIO especially with how buggy it has been in 1.10. Or because it would make Mek better? By your logic, Aidan should just remove all his transmitters since you can use their mods. :)

Well aware it would take a lot of work. Enough that it might get out on the "Mek v10" list but it's a suggestion none-the-less.

**Comment by VT-14** [comment]
To be truly honest, I think the transmitters are a bit of a rip off, and the reactor is a borderline case (conspicuously more powerful than Big Reactors).

But those are also generic enough to be fair game.  Reactors are a dime a dozen, and long range resource transportation is nothing new (for instance, Ender Chests).  


Placing multiple different pipes in one block space? Yeah, that's Ender IO's conduits.  I'm ok with multiple resources being transferred in one block space, but DON'T blatantly copy another mod; especially when it's one of the core components of the mod.  (enderIO.com's header "How many pipes in one block?")

**Comment by Utildayael** [comment]
Shrug. Mekanism reactor requires at least some level of effort to make and use. Big Reactors is easy mode for mass power gen. 

It's not really copying EnderIO, it's more copying real life where you can bundle pipes together. This isn't some magical fantasy concept. 

If it was copying say, the soul binder and spliced that would be a different story. 

If you want to see blatant copying go look at Tom's Mod. He managed to rip off IC2, Mek, AE2, TE and a few others all in one pack and it's blatantly done so. Hell I think his pipe tool is even called a configurator. ;)

**Comment by laz2727** [comment]
It's only a ripoff if you make it one.

**Comment by yutang13** [comment]
I still standby my idea which I submitted a while ago. A block which allows you to cross multiple pipes through each other. It would be fairly expensive and just acts as a one block hop across. So you don't have to worry so much about wiring your gas tubes, as is the pressurised tubes are annoying because they will just merge together and put the wrong gasses wherever.

https://github.com/aidancbrady/Mekanism/issues/3577

**Comment by Utildayael** [comment]
Pipe crossover would be useful too I agree. Even with the multi-pipe in same block we would still want it. 

Don't think it needs to be expensive tho. Should be a basic block if say gas line going N/S and power going E/W they would just pass through each other. Heck doesn't even need to be a block per say just a behavior change. :)

**Comment by yutang13** [comment]
I don't think having multiple pipes in one block is necessary because as mentioned that is EnderIO's signature thing.

I've come up with a (IMO) pretty good system for how Mekanism pipes should be handled.

1. Similar adjacent pipes can be disconnected from each other. Similar to how thermal dynamics handles it. Even something like a pipe plug from buildcaft would do. Just something to keep them from joining.
2.  New block: Pipe Hub
A fairly simple block which takes inputs from any Mekanism transmitters and ouputs them wherever it has been configured.
I think this is cool because it is multi-use. You can use it as a crossover block as I proposed or stick it on the back of a machine and feed multiple inputs through it. (Eg power, liquid, items and gas).
It would be like the transvector interface but with out the wireless capability. 
Maybe a much more expensive one that is wireless could be made too ;) 

With these changes you get around most of the annoying things about mekanism's transmitters without "ripping off" a mod.

**Comment by Utildayael** [comment]
Heh. I don't know if SleepyPants would say his mods signature is his conduits but hey... :)

I do like your ideas tho and that would be significantly less work for Aidan. Funny you mention TD as that was my go-to pipe in 1.7. Sad that TeamCOFH hasn't updated anything past 1.7. 

I'm just curious to hear Aidan's input on the subject. It might be something he was already looking at long term. It might also be a "nope don't like it" thing.

**Comment by yutang13** [comment]
Yeah I loved the TD pipes too. Mainly for power transfer but the higher tier filters and stuff on the itemducts were really helpful for skyblocks and sorting all the different items. Otherwise I just used ExtraUtilities for item transport. 

I must look at using the mekanism item pipes. I noticed they render the item like Logistics Pipes does which I love.

**Comment by Utildayael** [comment]
Ya the Mek pipes are nice. The only problem I have with the item pipes is a lack of filters. I mean you can color code and use a logistical sorter which works but it's a lot more of a pain than TD where I just toss filters on my end points and call it a day. In Mek you have to color the pipes which is nice in some cases. I kind of wish we could color all pipes which would take care of the connections you don't want problem since a blue pipe won't connect to a red pipe, etc. 

They don't seem as fast as TD item pipes but I could be wrong. Aidan fixed a bunch of stuff with them over the years so they're pretty solid. Really the item pipes are the most solid of any of them since they don't have buffers.

**Comment by D3nnis3n** [comment]
Would like this Feature very much, considering Mekanism is our main mod in 1.12 and EnderIO seems a bit dead at the moment, stuck on 1.10.
