### ISSUE TITLE
[Feature request] Installable upgrades for Atomic Disassembler

### ISSUE THREAD

**Issue by momerathe** [mekanism-mod/Mekanism#3904]
I really like the Atomic Disassembler, but there's one thing really holding it back as a mining tool - a lack of Silk Touch or Fortune.

Rather than go for vanilla enchants, I'd suggest installable upgrades that can be added to the tool (maybe through a dedicated workbench?). 

I'm sure there are other upgrades possible like a selectable 3x3 mode, or auto-smelt (though why you'd want auto smelt when you've got ore processing I've no idea). Maybe weapon enchants, too. Energy use should increase depending on the upgrade.

Obviously silk touch and fortune aren't compatible, but I'd go further and suggest that you should be limited to just one upgrade at any time. Makes life interesting.

**Comment by Protheus** [comment]
Would be nice to see this. he fortune, silk touch, 3x3, 5x5, 7x7 upgrades would we nice to have

**Comment by ixanza** [comment]
I really hope this one gets added. I was just thinking about hammers and 3x3 mining and stumbled upon this feature request. Maybe support for energy upgrades to make it more efficient on energy usage as well.

**Comment by Dragnier** [comment]
While I'm not super worried about a 3x3 mode, I do think there should be either a Fortune or Silk Touch upgrade available.

**Comment by Boolyman** [comment]
Man, I wish this request was getting some attention.  We really need a 3x3 and 5x5 mining mode, or this tool just pales in comparison to Actually Additions drills.

**Comment by scotty9090** [comment]
Agree with this.  I love the AD - including the way it looks and especially the ability to control its speed so I'm not accidentally taking out half my base.  However, it's hard to justify the AD when other options give you the ability to 3x3 (or 5x5) mine, and silk touch / fortune.  Adding the ability to enchant would handle the latter and I would guess is the easiest way to go about it.

**Comment by TechnosophyModPack** [comment]
Just a suggestion for how to make this work, I would, make a block that lets you modularly install and remove upgrades and modules to the atomic disassembler. See Modular Powersuits for an example of this type of setup. Then you shouldn't have to find an alternative key binding outside of Shift+Click (like Actually Additions drill) to implant the upgrades, and would be more immersive.

**Comment by pupnewfster** [comment]
Sounds interesting, could even almost more just be another tab in the security desk except have the thing be renamed so that it is more encompassing.

**Comment by TechnosophyModPack** [comment]
Would also suggest adding energy storage upgrades for the tool too

**Comment by kohlth** [comment]
alright building on top of this suggestions heres a really big idea based off this thats basicly a overhaul 

work station
the main machine/block, lets the player make/upgrade/change out parts on your tools and armor, requires power to change out and upgrade, is required to upgrade tool parts, maybe even make tool parts and maybe future items (i.e make upgrades craftable in this work station)?

all main parts start at basic rank and go up to ultimate
some upgrades require higher tiers

Atomic dissembler
the atomic disassembler has two parts, the handle and the head.
 the handle holds energy upgrades (power cells and such) and special modules to changing how the disassembler works. for example, a module that makes mining set stone variants free but you dont get any items, or a module that turns any mined logs turn into charcoal and sets attacked mobs on fire. (fortune and looting are a module) and a whole lot more. you can only hold 3 modules at a time on a max upgraded handle and some are incompatible. 
the head holds mode upgrades and upgrading it inceases attack speed and damage along with how efficent/ effective some upgrades are. mode upgrades are the diffrent modes you can flip through with shift right click like vein miner, fast , silk, vein miner + ,slow, and 3x3, (handle module that adds 5x5?)  

Jetpack
the jetpack has 3 parts, the body, the thrusters, and the maneuvering fins. 
the body contains the fuel storage and can either hold a tank or energy cell if the thrusters are powered instead of gas fueled. the body when tiered up lets you hold a better fuel container and also gain more protection, also has upgrades for fire protection, explosive protection and projectile protection
the thrusters come in two variants, gas and powered. powered use energy instead of hydrogen and are less efficent energy wise per tick but makes the jet pack way faster and easyer to recharge. both variants when tiered up increase in efficency and upward on regular mode thrust speed.
the maneuvering fins increase forward movement speed in air (makes hover mode viable for ok forward travel) when tiered up and can be upgraded to let the player glide forward using the shift key in regular mode. 

free runners
has two parts, the boots and asisstors
the boots when tiered hold more energy and give a small armor value
the asisstors when tiered give you a better efficency and small run speed boost. they can also be upgraded to give better jump, faster swim speed (including up and down swim speed), and deal damage to mobs you land on

helmet/mask thing
comes with two parts , the visor and helmet
the visor it a peice that does not gain any thing tiered straight up but allows for upgrades like night vision, zoom, better in water vision, and maybe a hud for things not usally seen in oneprobe and the like?
the helmet gains more energy storage and protection on tiering up, has a upgrade for water breathing using power or gains a small auto refilling/power refining internal oxygen tank?, and upgrades for protections like projectile and explosive

theres alot more but this is what i have so far, i just found out flame thrower can turn logs into charcoal lul, idk what heat mode does though...
