### ISSUE TITLE
Digital Miner feature-request: 'and' logic for filters

### ISSUE THREAD

**Issue by ghost** [mekanism-mod/Mekanism#4186]
Suppose the situation, I want to mine all ores that are generated by mod X. Currently, this is not doable - as some mods not only add ores to worldgen (e.g., gregtech adds numerous ores but numerous stones as well, so basically if I'll say "mine gregtech stuff" it woudl mine all ores plus all Granite, which might take a whole lot of space in the chunks)

What I want to propose it to have an AND logic to filters, e.g. a way to combine several filters (oredict filter + mod id filter in my case)

Thanks for your time making the great mod.

**Comment by VT-14** [comment]
It's already possible to set a separate filter for each ore you do want (OreDict each one, or use ItemStack if they don't work with the ore dictionary).

**Comment by nekoexmachina** [comment]
yes, its possible to set a separate filter for each ore. However, in case of GregTech ore generation, you have a big ore vein in each several chunks. When you run around the overworld, without an idea what exact ore is being generated in that chunk, you can have a problem:

-- OreDict filter ore* won't really work for finding out which ore this chunks have, since other mods ores might intervene and stall the process for a bit.
-- ModFilter filter GregTech won't work, since it would mine various GT stones for a while, and since stone veins are huge you will be stalled again

If its impossible or hard to have a combined "and" filter, yeah its possible to write down any kind of ore that GT adds by-hand, which is, though, a tedious proccess due to amount of them, especially if you would want to have several digital miners (as far as I know, there is no way to copy DM settings over to the other DM).

**Comment by tyler489** [comment]
Would also be cool to search by f3+H (localized name(i think)) if possible
