### ISSUE TITLE
Cannot insert more than a stack into YABBA barrel

### ISSUE THREAD

**Issue by DemonfangArun** [mekanism-mod/Mekanism#5218]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Logistical transporter pipes cannot insert more than 64 items into a YABBA barrel. Other item transport systems in the pack work normally. Multiple stacks can be pulled from the barrel using the transport pipes.

#### Steps to reproduce:
1. Attach logistical transporter to any side of a YABBA barrel
2. Attempt to pull multiple stacks of an item from any inventory to the barrel

#### Version (make sure you are on the latest version before reporting):
Forge: 2768
Mekanism: 9.4.13.349
YABBA: 1.1.2.29

**Comment by thiakil** [comment]
It probably gets capped to max stack size in the calculation by design

**Comment by Saereth** [comment]
This is happening in ender utils barrels and TE caches as well, once there are 64 items in the cache the logistical transporter stops inserting even though the destination is capable of holding thousands

**Comment by jupiterbjy** [comment]
![2019-01-25_15 45 29](https://user-images.githubusercontent.com/26041217/51730447-e33de100-20ba-11e9-8f99-b473b9197738.png)

Yeah, same goes for Cache. Not sending more than a stack. All other pipes so far I've tried worked well, obvious since most of them are using Itemduct code from Thermal Expansion itself.
Thumbs up for hardworking Mekanism devs who don't just copy-paste code from other mod :)

My guess would be: Cache only have single inventory slot with max stack size larger than 64, and Logistics Pipe is hard-coded to stop sending if each slot in connected storage gets 64 items. But this don't explain why Mekanism's Bin works..
