### ISSUE TITLE
Red/Green colour blindness

### ISSUE THREAD

**Issue by thiakil** [mekanism-mod/Mekanism#5298]
See comment at end of #2777

Ports that switch between input/output need to use more than just red/green.

**Comment by jburrows82** [comment]
The approach some other mods have done to indicate in/out is usually the four arrows which can be confusing when flipping in/out because of the shadowing depth illusion effect. 

Four arrows:
https://www.iconfinder.com/icons/391731/arrows_extend_full_fullscreen_maximize_resize_screen_icon

Members in the community with various colorblindness have said a more careful design such as [this](https://www.onlinewebfonts.com/icon/416618) is more intuitive for them.

**Comment by thiakil** [comment]
Fantastic, thanks!
