### ISSUE TITLE
Digital miner output is broken

### ISSUE THREAD

**Issue by lebanni** [mekanism-mod/Mekanism#5329]
The logistical pipe now connect to the lower part of the digital miner and items don't go to the chest (see videos).

Non working version :
Mekanism-1.12.2-9.6.7.360.jar
https://youtu.be/BNPap4-jxNs

Working version :
Mekanism-1.12.2-9.6.5.357.jar
https://youtu.be/aa89pOcb7m0

**Comment by thiakil** [comment]
Odd, this should be fixed post-Mekanica merge though. Try not letting the pipe touch the miner?

**Comment by lebanni** [comment]
I tried, same thing. Items are going back and forth the fisrt pipe.

**Comment by ToserBan** [comment]
I had a similar problem with the digital miner using Mekanism-1-12-2-9-6-7-359.jar
The miner produced way too much ore output. For example, without any speed upgrades, the miner added one ore per second into its internal storage, but at the rear panel the miner produced an output of about 16 ores per second. That are  not exact numbers, but its for sure a bug. Second, after the internal storage was full, the miner stopped counting down the remaining ores, as if there were infinite ores out there. I tried then the 357 version, like lebanni recommended and the miner output was normal.
I use the latest forge 14.23.5.2824, because one mod(industrial foregoing), has problems with the recommended older forge.

**Comment by thiakil** [comment]
The dupe bug should be fixed in the latest release, but that's separate from this auto eject issue

**Comment by lebanni** [comment]
v9.6.8.366.
Sorry, but still not working.

**Comment by thiakil** [comment]
This hasn't been merged to the `master` branch yet

**Comment by pupnewfster** [comment]
Should be fixed as of this release: https://minecraft.curseforge.com/projects/mekanism/files/2698323
